HAI 1.2
  CAN HAS STDIO?
  I HAS A FILM ITZ "MATRIX"
  
  VISIBLE "EVRENSEL SINEMA ARSIVI YUKLENIYOR..."
  VISIBLE "SISTEM ONAYLANDI. KABLO BAGLANTISI KOPARILDI."
  VISIBLE "KAPILAR ACILIYOR."
  
  VISIBLE FILM
KTHXBYE
